# Use official Python image as base
FROM python:3.11

# Set environment variables
ENV PYTHONUNBUFFERED 1

# Set working directory inside the container
WORKDIR /app

# Copy dependencies file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Run Django server
CMD ["python", "manage.py", "migrate", "0.0.0.0:8000"]

